### ISSUE TITLE
Determine application architecture

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/isotopes-and-atomic-mass#1]
In the original Java code, 'Isotopes and Atomic Mass' is actually embedded into the 'Build an Atom' file structure and the two simulations share a significant amount of common code. 'Build an Atom' has already been ported and I have been able to use several files which are shared between the two sims.  Where should we place the common files between these sims and how should I call on these files?

In the mean time, I am using shared 'Build an Atom' code by requiring it through 
```
      // sim with many shared files.
      BUILD_AN_ATOM: '../../build-an-atom/js'
```
in isotopes-and-atomic-mass-config.js, so 'Isotopes and Atomic Mass' is dependent on 'Build an Atom' for now.

@jbphet, since you wrote the original sim and ported 'Build an Atom', do you have any ideas on what would be best?

**Comment by aadish** [comment]
Shared repo exist now and shared between build an atom and IaAM
closing
