### ISSUE TITLE
branch: symbolNode

### ISSUE THREAD

**Issue by Luisav1** [phetsims/isotopes-and-atomic-mass#106]
The Symbol accordion box in IAAM will use the generalized SymbolNode from shred to avoid its duplication in IAAM, BAA, and Build a Nucleus - BAN (https://github.com/phetsims/build-a-nucleus/issues/9#issuecomment-1045454629). This branch will be deleted once MakeIsotopesScreenView.js no longer creates its own symbol node implementation and uses the SymbolNode from shred instead.

**Comment by zepumph** [comment]
This has been moved to master. Closing
