### ISSUE TITLE
replace toFixed with dot.Util.toFixed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/isotopes-and-atomic-mass#11]
This sim uses JavaScript's built-in toFixed. This function should not be used directly; it is notoriously buggy, and behavior differs depending on browser, because the spec doesn't specify whether to round or floor. Use dot.Util.toFixed, see its doc for details.

**Comment by jessegreenberg** [comment]
I have done most of the work on this port so far, I can clean this up.  Reassigning to myself.

**Comment by jessegreenberg** [comment]
Case of Math.toFixed has been replaced with dot.Util.toFixed.  Closing.
