### ISSUE TITLE
Should number of digits for isotope percentages behave like the Java sim?

### ISSUE THREAD

**Issue by jbphet** [phetsims/isotopes-and-atomic-mass#15]
When working on the first screen of the HTML5 version of Isotopes and Atomic Mass, @aadish and I noticed that the number of significant digits for the indicator that shows the abundance of a given isotope seems to vary by element.  I vaguely recall that there was a reason for this - perhaps that for some elements the value was only known to a certain number of significant digits - but I'm not sure.  It does look a little odd, so I think it would be worth double checking that this is the behavior that we want.

**Comment by amyh-phet** [comment]
@aadish and @jbphet 
Looking at the most recent NIST table for percent abundance of isotopes, it looks like the number of decimal places does vary among the different elements.   Although this looks odd in the sim, I think it would be best to follow the behavior seen in the Java version of the sim and report % abundance to the number of decimal places listed in the NIST table.

**Comment by aadish** [comment]
tested against the java sim behavior matches closing
