### ISSUE TITLE
Periodic table bug

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#16]
@jbphet  and @aadish   The elements listed in the last two rows on the periodic table are incorrect.   In row 6, Cs, Ba, and La are correct, but Ce-Hf are not in their correct positions on the table.   All elements in row 7 are incorrect.  This is the same as the issue we have in BAA.

[AP Periodic Table.pdf](https://github.com/phetsims/isotopes-and-atomic-mass/files/50064/AP.Periodic.Table.pdf)

**Comment by aadish** [comment]
@jbphet had alook at this and verified it was ok
