### ISSUE TITLE
New periodic table

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#18]
@aadish and @jbphet   

At design meeting on 12/3, decision was made to replace the full periodic table with a modified version of the table.  The attached artwork shows the new version of the periodic table in the default setting with hydrogen selected.
![periodic_table_isotopes_screen](https://cloud.githubusercontent.com/assets/13650180/11595850/c4ec68f0-9a6e-11e5-87ce-e504c5ae66a9.png)
![periodic_table_mixture_screen_001](https://cloud.githubusercontent.com/assets/13650180/11595856/cc2ee76e-9a6e-11e5-9952-0f2f274b265a.png)

Selectable buttons are 40 px squares in the mockup which should make the table the same width as the accordian boxes.

**Comment by aadish** [comment]
@amyh-phet This has been implemented. Can you test and verify this is what you are looking for behavior wise

**Comment by amyh-phet** [comment]
@aadish    Looks great and behaves as needed.  Closing issue.
