### ISSUE TITLE
Automated testing error - infinite loop!

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/isotopes-and-atomic-mass#20]
Example call stack when looping:

![isotopes-loop-stack](https://cloud.githubusercontent.com/assets/480878/11669974/a54c20ac-9dbc-11e5-91dc-caa2dcc2b7b0.PNG)

It's very reliable to reproduce, and assertions don't need to be enabled. It's also preventing me from using automated testing to test sims alphabetically after it (unless it gets removed or this gets solved).

**Comment by aadish** [comment]
have commented out the portion which is causing infinite loop will be looking further into it

**Comment by aadish** [comment]
fixed, closing
