### ISSUE TITLE
Isotopes labels on screen 1

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#21]
@aadish and @jbphet 
In IAAM 1.0.0-dev2, the isotope name and stable/unstable labels move as neutrons are added/removed from the nucleus.  This looks really jumpy as you interact with the sim.  Additionally, the unstable label for helium isotopes He-6, He-7, and He-8 are obscured by the scale.   Can we make the location of the labels static and base the location off the largest nucleon a user could create?
![iaam_dev2_h2_after](https://cloud.githubusercontent.com/assets/13650180/11750136/006c4320-9fef-11e5-9952-8d2095c5113e.png)
![iaam_dev2_h2_before](https://cloud.githubusercontent.com/assets/13650180/11750137/006d80f0-9fef-11e5-9321-fee24edba069.png)
![iaam_dev2_he8](https://cloud.githubusercontent.com/assets/13650180/11750139/0380c9a0-9fef-11e5-812c-7e7006e647cc.png)

**Comment by aadish** [comment]
@amyh-phet have fixed this have a look here
http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.4/isotopes-and-atomic-mass_en.html

**Comment by amyh-phet** [comment]
Looks great!  Closing issue.
