### ISSUE TITLE
User input for amounts of isotopes does not produce molecules on screen [Java]

### ISSUE THREAD

**Issue by bryo5363** [phetsims/isotopes-and-atomic-mass#22]
In the 'Mix Isotopes' section of the simulation I noticed that if the user selects 'More' and inputs a number greater than 100 for any molecule that the slider will snap to its maximum position of 100 but will not produce any molecules in the view. 

Steps to reproduce 
1) open sim
2) click 'mix isotopes'
3) click 'more' at the bottom
4) in the white space enter a number over 100. click away from the input box
5) the number will snap to 100 and the slider will be at its maximum position but no particles will be seen in the view portion of the sim.

**Comment by aadish** [comment]
This is not going to be a issue in HTML 5 version as we do not have a input box
