### ISSUE TITLE
Pressing 'More' clears the amount of molecules on the screen [Java]

### ISSUE THREAD

**Issue by bryo5363** [phetsims/isotopes-and-atomic-mass#24]
Steps to reproduce
1) open sim
2) click mix isotopes
3) drag isotopes onto the view screen
4) click 'more'. the initial particles will disappear
5) click 'less'. the initial particles will not be present

**Comment by aadish** [comment]
assigning to @amyh-phet in case she thinks behavior changes are needed

**Comment by amyh-phet** [comment]
@aadish  I think the current behavior from the Java version of the sim is fine. It looks like the original design team discussed this and concluded the current behavior was best.

**Comment by aadish** [comment]
HTML 5 version works same, closing
