### ISSUE TITLE
Switching to nature's mix takes a long time

### ISSUE THREAD

**Issue by aadish** [phetsims/isotopes-and-atomic-mass#26]
On the most recent dev version of IAAM which can be found here
http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.3/isotopes-and-atomic-mass_en.html

Switching to nature's mix takes a very long time. We need to work out performance improvement and requirements

**Comment by jbphet** [comment]
Some possible optimizations are:
+ Use a canvas node
+ Use a WebGL node
+ Have only a handful of particles and use the DAG nature of Scenery
+ Use pre-generated PNG images

**Comment by jbphet** [comment]
By the way, this refers to the second screen, which is the "Mix Isotopes" screen.

**Comment by jbphet** [comment]
Assigning to @amyh-phet to try this out and to come up with some specifications for the max allowable time to switch on our lowest performing platform, and to consider whether we should use a message of some kind (e.g. "Generating mix...").  From there we can assign to @jonathanolson to get recommendations on how best to optimize.

**Comment by amyh-phet** [comment]
@aadish and @jbphet  After discussing this in design meeting, let's try removing the gradient from the atoms in the display for Nature's mix. Another possible solution that we discussed was having the location of the 1000 particles pre-generated so when a user switches to Nature's mix the particles can be filled in at specific locations. If doing further optimization still leaves a lag time of >2 seconds, let's discuss other options.  I think the most troublesome part is the radio button does not immediately respond, leaving a user to wonder if the sim isn't working properly.

**Comment by aadish** [comment]
Tried to use the canvas node to render nature's mix. This has given slight performance improvement.
It can be seen in the dev-version 4 : http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.4/isotopes-and-atomic-mass_en.html
@amyh-phet can you check if it works

**Comment by amyh-phet** [comment]
@aadish   I tested the dev-4 version on the iPad 2 and although there is still a bit of a delay when toggling between My Mix and Nature's Mix, the delay is not unreasonably long (< 2 seconds).  Unless this presents an issue when interviewing, I think the fix you employed will suffice.

**Comment by amyh-phet** [comment]
No substantial lag seen in interviews, including on iPad 2.  Closing
