### ISSUE TITLE
Buckets refill after choosing slider view and switching elements.

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#28]
@aadish @amyh-phet @jbphet Here's the issue from the 1/7 design meeting:

1. Go to "Mix Isotopes" screen and pick an element.
2. Put some atoms into the box, placing all ten will make this issue more obvious but is not necessary.
3. Switch do a different element.
4. When viewing this new element, switch from the bucket view to slider view. You don't need to do anything else with this element.
5. Switch back to your original element (or really any element, doesn't matter) and voila, your bucket is refilled!

Note this next batch of atoms behave differently. With the original batch, trying to take an atom from the bottom of the bucket ends up grabbing one from the top, but here you will be able to take one from wherever you want. Furthermore, step 2 really isn't necessary. Switching to an element in step 5 will just layer the second batch over the first so you will still have more than ten atoms in a bucket even if you never placed any in step 2. Switching to ANY element from another element in slider view will cause this, even if you've never viewed the element before.

Seen on two Win 8.1 devices, FF and whatever browser @amyh-phet used.

**Comment by amyh-phet** [comment]
@aadish   Behavior occurred on Win 8.1 device in Chrome.  Thanks for logging this @phet-steele

**Comment by aadish** [comment]
fixed by commit number 1c5f5e5a3d96c07c49aa340e729443ba9ece35b4 , closing
