### ISSUE TITLE
Altered layout for Mix Isotopes screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#29]
Replace "Clear box" button with eraser button from common components. Move eraser button to under black play space on right side.  Move slider selection button under bucket selection button.   Move "Isotope Mixture" text, radio buttons, and corresponding text ("My mix" and "Nature's Mix") to right to allow for longer strings in translated sims.   Attached mock up shows new layout.
![mix_isotopes_eraser_button_01_08_16](https://cloud.githubusercontent.com/assets/13650180/12204692/faf4cefc-b5f2-11e5-9191-a78bde84910a.png)

**Comment by aadish** [comment]
@amyh-phet layout has been changed as per the requirements
Have a look here: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.4/isotopes-and-atomic-mass_en.html

**Comment by amyh-phet** [comment]
@aadish   The changes look good.  I think we still need some negative space below the periodic table.  Can we move the Percent Composition panel, Average atomic mass panel, and the buttons below the panels down to put a bit more white space between the bottom of the periodic table and the top of the yellow panels?   We can also reduce the font size on Percent Composition and Average Atomic Mass to make more room.

**Comment by amyh-phet** [comment]
New design implemented.  Adding additional changes to new issue - pixel polishing.  Closing issue
