### ISSUE TITLE
Pixel polishing

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#32]
@aadish   I have a list of items for pixel polishing on IAAM.  Is there a time we can meet to accomplish this together?  Let me know times you would be available.

The list includes:
- [x] Reducing the size of the Reset All button on both screens
- [x] Reducing the font size on the panel titles in both screens
- [ ] Reducing size of panels slightly in Mix Isotopes screen
- [x] Moving panels/buttons down on Mix Isotopes screen to allow for more white space under periodic table
- [x] Moving panels/buttons down on Mix Isotopes screen to add white space between panels
- [ ] Darken green color a bit on the atoms in buckets on the Mix Isotopes screen
- [x] Adjust labels on atoms in Mix Isotopes screen (Current labels don't fit well on atoms that have two letters in their symbols)

**Comment by aadish** [comment]
with discussion with @amyh-phet there is no need to reduce the size of panels as enough white space is available between panels and dark green color was only visible on @amyh-phet screen but it looked fine on other screens.
Other issues have been fixed, closing it
