### ISSUE TITLE
Percent composition labels not handled gracefully

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#39]
@aadish @amyh-phet On the Mix Isotopes screen, the labels begin to overlap with each other and the panel title if the pie chart has the appearance of a "left facing pac-man". Coolest to do this with sulfur:

Put all 10 atoms of Sulfur-36 into the play area, then one of each of the others (you'll have 13 total atoms in the play area) and the pie chart will look like this:

![left pacman](https://cloud.githubusercontent.com/assets/5863899/12625757/69e7c02c-c4f2-11e5-8077-8cba6725e2dd.PNG)

Placing more atoms into the play area slowly begins to fix this problem, and it's worth noting a RIGHT facing pac-man does not have a problem:

![right pacman](https://cloud.githubusercontent.com/assets/5863899/12625838/c714c3d0-c4f2-11e5-95ee-a3408a367750.PNG)

This happens for all elements. Tested on 1.0.0-dev.5 with Win 8.1 Chrome, iPad 2 iOS 9.3 beta (tycho), OSX 10.11.2 (dirac). For phetsims/tasks/issues/488.

Troubleshooting information:
Name: ‪Isotopes And Atomic Mass‬
URL: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.5/isotopes-and-atomic-mass_en.html
Version: 1.0.0-dev.5 2016-01-26 23:09:01 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"5a39ec57","branch":"master"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"57c99807","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"isotopes-and-atomic-mass":{"sha":"3d0c3bb9","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"953fe860","branch":"master"},"scenery-phet":{"sha":"e903fad2","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"shred":{"sha":"c1d4863f","branch":"master"},"sun":{"sha":"45c7d334","branch":"master"},"tandem":{"sha":"5388a9e4","branch":"master"}}

**Comment by aadish** [comment]
fixed, closing

**Comment by phet-steele** [comment]
@aadish @amyh-phet  not quite fixed in a similar situation as shown below. The two middle labels are overlapping:

![iaamlabels](https://cloud.githubusercontent.com/assets/5863899/13022880/4dcc00a4-d1a1-11e5-99fd-828af374bb96.PNG)

**Comment by aadish** [comment]
fixed, should be tested in next candidate

**Comment by phet-steele** [comment]
Labels look good to me in 1.0.0-rc.1.
