### ISSUE TITLE
iPad 2 Slider Performance (iOS 9.3 beta)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#40]
@aadish @amyh-phet the sliders on the Mix Isotopes screen don't preform the best on iPad 2 (tycho), with significant lag while adding atoms quickly. The performance slows as well when there are more and more atoms on the screen, so the sulfur sliders become slow quickly, as opposed to the beryllium sliders that only have one isotope available. In case you wanted the FPS, it drops to 5 fps while sliding, after being frozen for a bit. This number was from 1.0.0-dev.5. For https://github.com/phetsims/tasks/issues/488.

**Comment by aadish** [comment]
tried removing gradient but performance is not that great will be using canvas node

**Comment by aadish** [comment]
should be tested in next candidate

**Comment by phet-steele** [comment]
Performance is OK, @ariel-phet @amyh-phet please give you opinions. I'm on the fence, but if nothing else can be done then I'd feel okay as is.

**Comment by ariel-phet** [comment]
Tested on iPad 2 iOS 9.3.2

On Suflur if sliders are moved at a moderate speed performance is reasonable

If going to extremes quickly there is a noticeable lag, but I don't think it wold be pedagogically damaging.

Assigning to @amyh-phet to make the final call. It seems to me in the normal use case scenario we are fine

**Comment by ariel-phet** [comment]
@amyh-phet please feel free to close if you deem acceptable.

If not, I will get an estimate as to what could be done to eek out more performance :)

**Comment by amyh-phet** [comment]
@ariel-phet   When I looked at it on iPad 2 iOS 9.3.2, performance seemed reasonable to me as well.  I agree there is a lag if adding large numbers of atoms quickly, but I don't anticipate this would be done in normal use.  

Closing.
