### ISSUE TITLE
Sulfur-32 slider too far left for an iPad.

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#41]
@amyh-phet the sliders for sulfur are veeeeery close to the left edge. So much so that on an iPad, the leftmost slider is very difficult to slide without accidentally doing that weird iPad "slide to the right to go back to the previous page" thing. I don't know what to call it, but @amyh-phet saw what I'm talking about :smile:. I'd recommend we resize the sliders, or move them farther from the left edge. Otherwise, the slider for Sulfur-32 will be largely unusable. This only happens for sulfur since it is the only element with four isotope sliders that take up this much room.

Tested on 1.0.0-dev.5 with iPad 2 iOS 9.3 beta (tycho). For https://github.com/phetsims/tasks/issues/488.

**Comment by amyh-phet** [comment]
@aadish   Can we reduce the size of the sliders on only the S screen?

**Comment by amyh-phet** [comment]
@aadish   The sliders seem to work better - less chance of sliding the entire screen instead of just moving the slider.   Let's see if there are issues when we interview.

**Comment by amyh-phet** [comment]
No issue observed with interviews.  Closing.
