### ISSUE TITLE
Nature's Mix and My Mix particles have different appearance [dev.5]

### ISSUE THREAD

**Issue by bryo5363** [phetsims/isotopes-and-atomic-mass#43]
Test device: Acer Aspire R13 (Bryan's Personal Computer)

Operating System: Windows 10

Browser: Chrome 47.0.2526.111 m

Problem description: The particles in my mix and nature's mix have a different appearance

Steps to reproduce:

Severity:

Screenshots:
Below is a screen shot of 'My Mix'

<img width="751" alt="iosotopes_my_mix" src="https://cloud.githubusercontent.com/assets/7717368/12627165/87699bc8-c4f9-11e5-9d8b-eb7225f2ab18.PNG">

Below is a screen shot of 'Nature's Mix'

<img width="725" alt="iosotopes_nature_mix" src="https://cloud.githubusercontent.com/assets/7717368/12627171/9c7bb6e0-c4f9-11e5-9429-f10b81fdeab9.PNG">

Troubleshooting information (do not edit):
Name: ‪Isotopes And Atomic Mass‬
URL: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.5/isotopes-and-atomic-mass_en.html
Version: 1.0.0-dev.5 2016-01-26 23:09:01 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1280x595
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"5a39ec57","branch":"master"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"57c99807","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"isotopes-and-atomic-mass":{"sha":"3d0c3bb9","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"953fe860","branch":"master"},"scenery-phet":{"sha":"e903fad2","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"shred":{"sha":"c1d4863f","branch":"master"},"sun":{"sha":"45c7d334","branch":"master"},"tandem":{"sha":"5388a9e4","branch":"master"}}

**Comment by phet-steele** [comment]
@bryo5363 this was done on purpose to improve performance. See https://github.com/phetsims/isotopes-and-atomic-mass/issues/26#issuecomment-170040477
