### ISSUE TITLE
Placing incorrect atoms into the play area via element selection buttons

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#46]
Another way to cause an incorrect element to be placed in the play area:

Turns out the smaller periodic table buttons have a consequence of firing on a mouse up event (in other words, the element selected doesn't change until the mouse button is released as opposed to when the mouse button is pressed).
1. Go to the Mix Isotopes screen, and choose an element.
2. Place at least one atom into the play area.
3. Switch to a different element, then switch back to your original element.
4. Using the atom that was placed in the play area, drag it towards the small periodic table. Release your mouse and the atom once you cursor is over one of the small element buttons.

![isoatma3](https://cloud.githubusercontent.com/assets/5863899/12631351/168900b4-c50e-11e5-8234-61e7cb1466aa.gif)

Tested in 1.0.0-dev.5 with Win 8.1 Chrome and OSX 10.11.2 (dirac). For phetsims/tasks/issues/488.

Troubleshooting information:
Name: ‪Isotopes And Atomic Mass‬
URL: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.5/isotopes-and-atomic-mass_en.html
Version: 1.0.0-dev.5 2016-01-26 23:09:01 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"master"},"axon":{"sha":"5a39ec57","branch":"master"},"babel":{"sha":"db982666","branch":"master"},"brand":{"sha":"8c6f9c04","branch":"master"},"chipper":{"sha":"57c99807","branch":"master"},"dot":{"sha":"ddf82014","branch":"master"},"isotopes-and-atomic-mass":{"sha":"3d0c3bb9","branch":"master"},"joist":{"sha":"4c228a32","branch":"master"},"kite":{"sha":"4a947119","branch":"master"},"phet-core":{"sha":"874a703d","branch":"master"},"phetcommon":{"sha":"3db92af3","branch":"master"},"scenery":{"sha":"953fe860","branch":"master"},"scenery-phet":{"sha":"e903fad2","branch":"master"},"sherpa":{"sha":"bf82eb95","branch":"master"},"shred":{"sha":"c1d4863f","branch":"master"},"sun":{"sha":"45c7d334","branch":"master"},"tandem":{"sha":"5388a9e4","branch":"master"}}

**Comment by aadish** [comment]
@samreid Fixing this issue required adding the button listener for periodic table cell. This involved some change in tandem emitters.
The code change piece of code is here https://github.com/phetsims/shred/commit/a1fe879177bb988efa0ac3f4e3bd4e0e04538f6f

Can you review it to see if it doesn't break tandem

**Comment by samreid** [comment]
I reviewed the change set and looked at the output from the periodic table cells, all seems good.  Anything else to do here @aadish?

**Comment by aadish** [comment]
thanks @samreid for reviewing nothing else has to be done. Closing this as the behavior is working fine.
