### ISSUE TITLE
create dev version for use in interviews

### ISSUE THREAD

**Issue by jbphet** [phetsims/isotopes-and-atomic-mass#48]
@amyh-phet is preparing to do interviews on this simulation, and @aadish is putting together a version to use for this.  This issue will track progress towards having a good release ready in time.

**Comment by aadish** [comment]
@amyh-phet Please find the dev version [here](http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.6/isotopes-and-atomic-mass_en.html) 
Have a look at it and if any issues are there that will be our top priority to resolve

**Comment by amyh-phet** [comment]
@aadish  Thanks! I will look to see if there are any issues with the current dev version.

**Comment by amyh-phet** [comment]
@aadish    The current dev version looks good (of course I'm not @phet-steele).   @phet-steele  if you have time on Friday or Monday, could you check the sliders on sulfur to see if we still have the problem with spacing on the left side of the screen?  If you don't have time, I will check when I get to the office on Tuesday morning.   Interviews are currently scheduled for 2/17 and 2/18.

**Comment by phet-steele** [comment]
@amyh-phet I can certainly look at it. Maybe Friday...maybe Monday...maybe both, definitely before interviews.

**Comment by aadish** [comment]
@phet-steele Thanks for pointing out the issues. Here is the dev-release which fixes these issues http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-dev.7/isotopes-and-atomic-mass_en.html

Can you please look at it before the interviews

**Comment by amyh-phet** [comment]
Thanks @aadish.   Looks good.   Will see how things go - two interviews today.

**Comment by amyh-phet** [comment]
Interviews in progress. Closing
