### ISSUE TITLE
Resetting on hydrogen doesn't return the atoms

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#49]
@aadish pressing the reset all button on the Mix Isotopes screen while playing with hydrogen will not return the atoms to the bucket. They just disappear;

![iaam1](https://cloud.githubusercontent.com/assets/5863899/13086286/d723f05e-d49f-11e5-9382-bcb7f848d396.gif)

Switching to slider view or resetting on a different element fixes the issue (seen in the above video).

Seen on all platforms in 1.0.0-dev.6. Needs to be fixed for #48, so high priority before tomorrow.

**Comment by phet-steele** [comment]
Also pressing the eraser fixes this.

**Comment by phet-steele** [comment]
@aadish, in the current version of master (2/26 noon), resetting while in slider view for hydrogen will not return the atoms to the bucket. So far it looks like only hydrogen has this problem:

![iaam3](https://cloud.githubusercontent.com/assets/5863899/13362395/67408cea-dc81-11e5-9b35-2fbe50c045cc.gif)

**Comment by aadish** [comment]
fixed, would be tested in next test candidate

**Comment by phet-steele** [comment]
Fixed in 1.0.0-rc.1.
