### ISSUE TITLE
sim doesn't start

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/isotopes-and-atomic-mass#5]
master, all platforms. Here's the console output:

![screenshot_480](https://cloud.githubusercontent.com/assets/3046552/6535421/25d52826-c402-11e4-8209-234a76017dd8.png)

**Comment by samreid** [comment]
Fixed above, reassigning to @pixelzoom.

**Comment by pixelzoom** [comment]
Thanks, closing.
