### ISSUE TITLE
Layout changes after the interview for Screen 2

### ISSUE THREAD

**Issue by aadish** [phetsims/isotopes-and-atomic-mass#50]
After the interviews @jbphet made some quick changes to the layout which look like this at the moment

![image](https://cloud.githubusercontent.com/assets/4546788/13185956/fbf76c5e-d700-11e5-92ce-63dabd00f08c.png)

@jbphet and @amyh-phet discussed this and figured that chamber box can be reduced a bit.

@amyh-phet Can you describe what should the layout finally look like and then we can make changes accordingly.

**Comment by amyh-phet** [comment]
@aadish  Below are two screen shots of what the final layout should look like.  I think that reducing the height of the black box slightly would give a bit more space above and below the sliders or buckets.  Let me know if I can further clarify layout changes.
![2016_02_19_new_layout_mix_isotopes](https://cloud.githubusercontent.com/assets/13650180/13186456/8e270218-d703-11e5-860e-e1da4453f383.png)
![2016_02_19_buckets](https://cloud.githubusercontent.com/assets/13650180/13186458/911caa5e-d703-11e5-8de0-e2ccc0478b69.png)

**Comment by amyh-phet** [comment]
@aadish  I have a few minor pixel polishes.  It might be better to meet in person to make the minor changes to layout if you are available.

**Comment by aadish** [comment]
Sure @amyh-phet we can meet tomorrow. I will come by your office.

**Comment by amyh-phet** [comment]
Thanks.

**Comment by amyh-phet** [comment]
@aadish    One last layout tweak.  On the Mix Isotopes screen, the Isotope Mixture label needs to be moved down closer to the labels and radio buttons.    As far as I know, this is the last minor change!

**Comment by aadish** [comment]
fixed, closing
