### ISSUE TITLE
Buckets return on Mix Isotopes Screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#51]
@aadish    On the Mix Isotopes screen, once sliders have been selected, sliders should remain selected if a user switches to a different element.  For instance, if a user is on hydrogen, changes from buckets to sliders but then selects lithium, the sliders for lithium should appear instead of buckets.  Current version of the sim defaults to buckets when a new element is selected.

**Comment by aadish** [comment]
@amyh-phet current implementation is in sink with java version. 

Is the behavior needs to change from the java version?

**Comment by amyh-phet** [comment]
@aadish    Would this be an expensive fix? I recognize that current behavior is from the Java version of the sim.  I would prefer to keep the slider/bucket selection the same if a user changes to a new element.  Sorry I didn't catch this behavior in the Java sim until now.

**Comment by ariel-phet** [comment]
Expensive or not, this is a change that should be made, it brings a more consistent and logical user experience. Of course, no need to worry about the Java sim, that can stay as is.

**Comment by amyh-phet** [comment]
@aadish   The new behavior looks great.  Thank you for implementing this.

**Comment by aadish** [comment]
fixed would be tested in next test candidate

**Comment by phet-steele** [comment]
Behaviour implemented!
