### ISSUE TITLE
Layering behavior

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#53]
On the Mix Isotopes screen, when a user selects an atom from one of the buckets, the atom should move to the top of the layer.  When dragging the atom, it should appear in front of most items on the screen (for example, the bucket/slider buttons, periodic table, and percent composition/average atomic mass panels).  The only exception would be the buckets, which should remain at the very top of the layer.

**Comment by aadish** [comment]
this has been fixed and would be tested in next test candidate

**Comment by phet-steele** [comment]
Layers look great in 1.0.0-rc.1!
