### ISSUE TITLE
Neutrons fall diagonally back to bucket

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#58]
Just doing some initial playing around with this sim to get familiar. Dropping a neutron above the empty part of the bucket causes it to fall diagonally, on top of the others. This happens unless the drop height is fairly low.

Maybe not a bug per se, but unexpected behavior.

(#57)

**Comment by aadish** [comment]
This is done to maintain the stacking of particles in the bucket, same behavior exist in build an atom, closing this as it is not an unexpected behavior
