### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/isotopes-and-atomic-mass#6]
I can't confirm this because the sim doesn't run (see #5). But it looks like particles are filled with 'red'. They should probably be filled with PhetColorScheme.RED_COLORBLIND.

**Comment by pixelzoom** [comment]
InteractiveIsotopeNode line 100:
>  var particleView = new Circle( 10, { fill: 'red' } );

**Comment by jessegreenberg** [comment]
Sorry, circles here were just being used for visual debugging and they have been removed.  particleView variables are now ParticleView node objects.  ParticleView colors are defined in shred and the color will be changed there through issue phetsims/shred#2

**Comment by aadish** [comment]
RED_COLORBLIND is used for particles and periodic table highlighting, closing
