### ISSUE TITLE
Minor whitespace and indentation issues throughout

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#60]
I'll post a few examples. Would be good to run a formatting tool throughout the whole sim.

Spacing:

https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/common/view/PieChartNode.js#L123

https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/make-isotopes/model/MakeIsotopesModel.js#L26

Indentation (should be 2 spaces):

https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/make-isotopes/model/MakeIsotopesModel.js#L192-L196

(#57)

**Comment by aadish** [comment]
indentation commit https://github.com/phetsims/isotopes-and-atomic-mass/commit/b1b129b97e5e5cdbe267f7d4103876910463c670
