### ISSUE TITLE
`that = this` ?

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#61]
Might just be my inexperience...is `var that = this` idiomatic for naming the enclosing scope for use inside nested functions? I tend to see (and use) conventions like `var self = this` (perhaps my Python background) or something like `var thisNode = this`.

It is used in MakeIsotopesModel and MixIsotopesModel. Feel free to close if this not a deviation from the code standards.

(#57)

**Comment by aadish** [comment]
fixed, closing
