### ISSUE TITLE
Undocumented parameters

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#62]
https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/make-isotopes/model/MakeIsotopesModel.js#L159-L163

https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/make-isotopes/model/MakeIsotopesModel.js#L159-L163

https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/make-isotopes/view/MakeIsotopesScreenView.js#L44-L48

This is not an exhaustive list. Please go through and check the JSDoc for all functions.

(#57)

**Comment by andrewadare** [comment]
A few undocumented functions remain in IsotopeProportionsPieChart.

**Comment by aadish** [comment]
@andrewadare fixed that, closing
