### ISSUE TITLE
Replace Math.round with dot.Util.roundSymmetric if necessary

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#65]
From the code review checklist:

> Is Math.round used where dot.Util.roundSymmetric should be used? Math.round does not treat positive and negative numbers symmetrically, see phetsims/dot#35 (comment)

Files containing Math.round:

 - MakeIsotopesScreenView.js
 - MixIsotopesModel.js
 - MixIsotopesScreenView.js

(#57)

**Comment by andrewadare** [comment]
I didn't check the domain of the numbers to be rounded. The replacement may not be necessary if the numbers are guaranteed to be positive, but please verify.

**Comment by aadish** [comment]
fixed, closing
