### ISSUE TITLE
Set pickable with enabled?

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#67]
Should these settings

https://github.com/phetsims/isotopes-and-atomic-mass/blob/96c79c27c33a4173c1d405d8fff8808f13abcfba/js/mix-isotopes/view/ControlIsotope.js#L83-L84

also be accompanied by a pickable setting? From the CRC:
 > User interface components with enabled:false should also have pickable:false

If this is okay, please close.

(#57)

**Comment by aadish** [comment]
for buttons pickable setting is handled by button class, so no need to explicitly set pickable to false

closing
