### ISSUE TITLE
Fix comment

### ISSUE THREAD

**Issue by andrewadare** [phetsims/isotopes-and-atomic-mass#72]
Can you make this comment clearer?

https://github.com/phetsims/isotopes-and-atomic-mass/blob/0b6d85051ba9c57010d375f4d04a597805beb4af/js/make-isotopes/view/TwoItemPieChartNode.js#L70

**Comment by aadish** [comment]
@andrewadare does the comment makes sense now

**Comment by andrewadare** [comment]
Sorry to drag out this minor issue. If you find [my suggestion](https://github.com/phetsims/isotopes-and-atomic-mass/commit/e9abba750c89709809d7ea5568e43008ee207a27#commitcomment-17523232) agreeable, just add it and close. Thanks!

**Comment by aadish** [comment]
no issues @andrewadare this is also a learning experience for me, fixed closing
