### ISSUE TITLE
Hydrogen buckets disappear on reset

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#73]
1. On hydrogen, go to Nature's mix
2. Reset
3. Viola, no buckets:

![nobuck](https://cloud.githubusercontent.com/assets/5863899/15302212/051c74b6-1b6f-11e6-97b4-1176aaa50116.PNG)

Seen on all Win 10 browsers. For phetsims/tasks/issues/595

Troubleshooting information:
Name: ‪Isotopes and Atomic Mass‬:‪Isotopes and Atomic Mass‬
URL: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-rc.1/isotopes-and-atomic-mass_en.html?stringTest=double&dev&screens=2.1
Version: 1.0.0-rc.1 2016-05-16 18:47:41 UTC
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Language: en-US
Window: 2560x1315
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"5e33541f","branch":"HEAD"},"babel":{"sha":"0bb532ea","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"chipper":{"sha":"64ea5afc","branch":"HEAD"},"dot":{"sha":"bf6f038b","branch":"HEAD"},"isotopes-and-atomic-mass":{"sha":"6b5dc8c6","branch":"HEAD"},"joist":{"sha":"4e95673d","branch":"HEAD"},"kite":{"sha":"dce9765e","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"eab7fb7f","branch":"HEAD"},"scenery":{"sha":"12bb4bd8","branch":"HEAD"},"scenery-phet":{"sha":"436bf61d","branch":"HEAD"},"sherpa":{"sha":"ab4d5c14","branch":"HEAD"},"shred":{"sha":"fa882f4f","branch":"HEAD"},"sun":{"sha":"9f2d40d5","branch":"HEAD"},"tandem":{"sha":"0ad35fb7","branch":"HEAD"}}

**Comment by brroberts1231** [comment]
Fixed, closing.
