### ISSUE TITLE
Artifacts when collapsing menus on IE11

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/isotopes-and-atomic-mass#74]
Test device: Schrodinger

Operating System: Win 8

Browser: IE11

Problem description: When you collapse any of the boxes, the horizontal line at the bottom of the box remains where it was. Only seen on IE11.

Severity: low

Screenshots:
![isotopes atomic mass](https://cloud.githubusercontent.com/assets/11947677/15334727/a8a887ec-1c2c-11e6-819f-67eb0d845d01.png)

Troubleshooting information (do not edit):
  
Name: ‪Isotopes and Atomic Mass‬

URL: http://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.0-rc.1/isotopes-and-atomic-mass_en.html

Version: 1.0.0-rc.1 2016-05-16 18:47:41 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; InfoPath.3; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; rv:11.0) like Gecko

Language: en-US

Window: 1536x770

Pixel Ratio: 1.25/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 8192x8192

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"axon":{"sha":"5e33541f","branch":"HEAD"},"babel":{"sha":"0bb532ea","branch":"master"},"brand":{"sha":"bb1cfcc6","branch":"HEAD"},"chipper":{"sha":"64ea5afc","branch":"HEAD"},"dot":{"sha":"bf6f038b","branch":"HEAD"},"isotopes-and-atomic-mass":{"sha":"6b5dc8c6","branch":"HEAD"},"joist":{"sha":"4e95673d","branch":"HEAD"},"kite":{"sha":"dce9765e","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"eab7fb7f","branch":"HEAD"},"scenery":{"sha":"12bb4bd8","branch":"HEAD"},"scenery-phet":{"sha":"436bf61d","branch":"HEAD"},"sherpa":{"sha":"ab4d5c14","branch":"HEAD"},"shred":{"sha":"fa882f4f","branch":"HEAD"},"sun":{"sha":"9f2d40d5","branch":"HEAD"},"tandem":{"sha":"0ad35fb7","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
@brroberts1231 reminder...please reference test issue :)

**Comment by brroberts1231** [comment]
Right. phetsims/tasks#595

**Comment by brroberts1231** [comment]
Fixed, closing.
