### ISSUE TITLE
User feedback: spacing between characters

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/isotopes-and-atomic-mass#78]
Submitted by Sandor Nagy:

> Look at the screenshot below. Ther should not be space between the number and the % symbol. So it should be 100%.
> 
> There should be a space between the numerical value and the unit. So it should be 9.01218 u.
![image001](https://cloud.githubusercontent.com/assets/5090275/18793480/395ca93e-8178-11e6-983f-aab6052d12a2.png)

@ariel-phet can you comment on the above feedback? @jbphet asked me to assign to @aadish for now.

**Comment by ariel-phet** [comment]
There is no space between the number and percent on the first screen, so we should be consistent.

Generally speaking, in writing, there is no space, ie "96.3%"

The user is also correct about the units, I am surprised we missed this. certainly there should be a space between the number and the unit "amu" on the second screen.

**Comment by ariel-phet** [comment]
@aadish we should probably do a maintenance release

**Comment by aadish** [comment]
@oliver-phet @ariel-phet the fix has been made and maintenance release has been done for the same and is live on the website

@oliver-phet can you let Sandor know changes have been made

**Comment by oliver-phet** [comment]
Thanks @aadish ! Will report to user.

**Comment by oliver-phet** [comment]
Ah yes, very nice!
