### ISSUE TITLE
isotopes-and-atomic-mass fails lint

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/isotopes-and-atomic-mass#8]
To reproduce, run "grunt lint".

**Comment by jbphet** [comment]
I discussed with with @jessegreenberg today and am assigning to him for now.  He will work with @jasm32851 to make sure that he is aware of lint and is running it regularly.  At some point it will probably make sense to assign to @jasm32851.

**Comment by aadish** [comment]
Working on it now and it does not give error while running lint and would be maintaning that
