### ISSUE TITLE
How can I add more Proton, Neutron, Electron in trajectory

### ISSUE THREAD

**Issue by tuzenvn** [phetsims/isotopes-and-atomic-mass#83]
In your site have 10 items of  Proton, Neutron and Electron.
I need to more items (about 20 items for each). How can I add more?

Please help me

Thanks

**Comment by ariel-phet** [comment]
@tuzenvn The number of items available in the simulation is chosen to be constrained on purpose. If you wish to add more, that would need to be done by someone with programming knowledge. Our code is open-source, and certainly this could be accomplished, but our team has not plans to change this constraint on the published simulation.
