### ISSUE TITLE
Fluorine 18 and 19 should have different amu

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#88]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/300
Bot F-18 and F-19 say amu=18.99840 on the isotopes screen.  According to Wikipedia F-18 should be 18.0009373(5).
**Steps to reproduce:**
1. Go to the Isotopes screen
2. Select F on the periodic table
3. Select Atomic Mass (amu)
4. Remove a neutron to compare the amu of F-18 and F-19

**Screenshots:**
![amudoesntchange](https://user-images.githubusercontent.com/41024075/55577343-a3096900-56d0-11e9-8ee3-0a0d856bfe2c.gif)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Isotopes and Atomic Mass‬
URL: https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.1/phet/isotopes-and-atomic-mass_en_phet.html
Version: 1.1.0-rc.1 2019-03-22 21:49:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
Another good catch.  It should now be fixed.

**Comment by KatieWoe** [comment]
Looks good in 1.1.0-rc.2
