### ISSUE TITLE
Slight pointer area overlap on Isotopes screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#89]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/300
The touch pointer area to expand/contract the symbol box overlaps the pointer areas of the periodic table a bit.
**Steps to reproduce:**
1. Set showPointerAreas
2. Go to the isotopes screen
3. Observe overlap

**Screenshots:**
![pointerareaoverlaps](https://user-images.githubusercontent.com/41024075/55579919-9be55980-56d6-11e9-9901-4609853d35c3.png)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Isotopes and Atomic Mass‬
URL: https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.1/phet/isotopes-and-atomic-mass_en_phet.html?showPointerAreas
Version: 1.1.0-rc.1 2019-03-22 21:49:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This is in published version

**Comment by jbphet** [comment]
I reduced the dilation value used to 12 from 16, and that appears to have done the trick.  Here is what it looks like now:
![image](https://user-images.githubusercontent.com/3082831/56065515-4b9f7480-5d32-11e9-819f-7b0420ab54d8.png)

**Comment by KatieWoe** [comment]
Looks good .1.0-rc.2
