### ISSUE TITLE
Trace string has no max width

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#90]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/300
When string test is long you can see that the string "Trace" does not get smaller and overlaps many other aspects of the sim when present.  This can be seen a bit with stringTest=double, as the box gets bigger, but it is not yet a problem at that point.
**Steps to reproduce:**
1. Set stringTest=long
2. Go to the first screen
3. Go to Fluorine
4. Make sure the abundance in nature box is open
5. Make the F-18 isotope (This can be done with any element isotope that is considered "trace")

**Screenshots:**
![longstringtests](https://user-images.githubusercontent.com/41024075/55581043-2a5ada80-56d9-11e9-9faa-e9c45cf5061f.png)

**Troubleshooting information (do not edit):**

<details>

Name: 12345678901234567890123456789012345678901234567890
URL: https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.1/phet/isotopes-and-atomic-mass_en_phet.html?stringTest=long
Version: 1.1.0-rc.1 2019-03-22 21:49:06 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
Good catch.  There was no max width on the readout because it previously was always limited to a fixed number of digits.  I've added one, and fixed an issue with how the layout looks with long strings.

**Comment by KatieWoe** [comment]
Looks ok in rc.2
