### ISSUE TITLE
Update teacher tips (trace abundance)

### ISSUE THREAD

**Issue by arouinfar** [phetsims/isotopes-and-atomic-mass#92]
For https://github.com/phetsims/QA/issues/300

The changes made in #85 should be documented in the Teacher Tips.

**Comment by arouinfar** [comment]
Tips have been updated and uploaded to Drive.

**Comment by jbphet** [comment]
The change to support "trace" is now deployed.  @arouinfar - I'm not sure if this implies that the teacher tips need to be deployed or not, but I thought I'd let you know.

**Comment by arouinfar** [comment]
The updated Teacher Tips have been deployed, thanks @jbphet.
