### ISSUE TITLE
Decimals on 2nd screen no longer reach 4 digits

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#95]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/310
In the published version of the sim, some elements show an abundance in nature percentage with 4 decimal places.  In the rc this only reaches 3.  This affects Hydrogen, Helium, and Argon.  Particularly noticeable in Helium as it leads to percentages of 0% and 100%
**Steps to reproduce:**
1. Open the rc and the published version in different tabs
2. On both, go to the mixtures screen
3. On both, select He
4. On both, select natures mix
5. compare the percentages in the pie charts

**Screenshots:**
RC
![rcdecimals](https://user-images.githubusercontent.com/41024075/56533651-58cc1880-6515-11e9-8daf-de173f0a44e7.png)
Published
![pubdecimals](https://user-images.githubusercontent.com/41024075/56533678-62ee1700-6515-11e9-9700-6503382b125e.png)

Troubleshooting information (do not edit):

<details>

Name: ‪Isotopes and Atomic Mass‬
URL: https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-rc.2/phet/isotopes-and-atomic-mass_en_phet.html
Version: 1.1.0-rc.2 2019-04-22 19:12:45 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
This does seem to have been a problem in rc.1 as well

**Comment by arouinfar** [comment]
Nice find @KatieWoe. Four decimals does seem preferable @jbphet.

**Comment by jbphet** [comment]
This was due to a change that was made to the method that retrieves abundance data from `AtomIdentifier` that was not correctly compensated for showing percentage data.  This has been fixed.

**Comment by jbphet** [comment]
Fixed and deployed - closing.
