### ISSUE TITLE
TypeError: Class constructor cannot be invoked without 'new'

### ISSUE THREAD

**Issue by samreid** [phetsims/isotopes-and-atomic-mass#99]
In https://github.com/phetsims/tasks/issues/1044, Particle.js was converted to `class` but js/mix-isotopes/model/MovableAtom.js extends it using `inherit` which causes this error on CT:

> TypeError: Class constructor cannot be invoked without 'new'

I don't see any other subtypes of MovableAtom--I'll try converting it to a `class` to see if it helps.

**Comment by samreid** [comment]
Proposed fix committed, reassigning to the responsible dev for review & testing.

**Comment by pixelzoom** [comment]
Thanks for taking care of that, sorry I missed the MovableAtom subclass.

**Comment by jbphet** [comment]
Thanks for the fix @samreid.  Closing.
